### ISSUE TITLE
Cannot get tag highlights

### ISSUE THREAD

**Issue by kajetan-mazur** [sethmcleod/language-pug#3]
Hi 

I have install Your package on atom but it does not highlight tags. Something is highlighting them
![image](https://user-images.githubusercontent.com/22578157/27768407-0e8fe0a8-5f13-11e7-8c20-6136339f0ded.png)
But i have no idea what cause i have like 102 packages. Yours is the last one i have install. After im moving my lorem impsum text into new line but still on the same p tag it highlights the first word which it should not highlight
![image](https://user-images.githubusercontent.com/22578157/27768412-4eb5a550-5f13-11e7-867f-1e9b513bb3d0.png)
Do You have any idea how to fix it?

**Comment by sethmcleod** [comment]
Hi @kajetan-mazur!

In order to write your text on multiple lines, you'll need to use _piped text_ or a _plain-text block_. Here an example showing what those looks like. You can check out the Pug plain-text [documentation](https://pugjs.org/language/plain-text.html) for more information.

![image](https://user-images.githubusercontent.com/7340187/27804865-3c4c36d0-5fff-11e7-8b54-e9f7fb120157.png)
